# Site settings
title: Stefan's Game Collection
email: stefpet@gmail.com
description: >
    Fork me on <a href="https://github.com/stpe/games">Github</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stpe.github.com" # the base hostname & protocol for your site
twitter_username: stpe
github_username:  stpe
instagram_username: stpe

# Build settings
markdown: kramdown

safe: true
lsi: false

exclude:
 - Gruntfile.js
 - grunt-gss.json
 - package.json
 - README.md
 - gss-key.pem
